### ISSUE TITLE
Unable to add text and an element as children together

### ISSUE THREAD

**Issue by mohitmayank** [a-tarasyuk/tag#2]
```
tag('label', [
    tag('input', {type='text', name='sample'}),
    'text'
])

```
results in
`<label>text</label>`

added a pull request for the same. 
https://github.com/a-tarasyuk/tag/pull/1

**Comment by mohitmayank** [comment]
also, it's a very nice utility. small and useful. thanks @a-tarasyuk

**Comment by a-tarasyuk** [comment]
#3
