### ISSUE TITLE
unable to create self closing tags

### ISSUE THREAD

**Issue by mohitmayank** [a-tarasyuk/tag#3]
unable to create both -
`tag('input', {'type' : 'text'})` and `tag('br')` 
getting 
`<inout>[object Object]</input>` and `<br></br>`

**Comment by mohitmayank** [comment]
update pull request. https://github.com/a-tarasyuk/tag/pull/1

**Comment by a-tarasyuk** [comment]
Thanks you very much for your response, I've done refactoring and fix two issues, you can check new version 

Examples - https://jsfiddle.net/uks8ue7r/1/
